build:
  image: drone/golang:1.5
  commands:
    - echo 'Build teaci/msys32 image using drone docker plugin...'

notify:
  irc:
    prefix: build
    nick: msys32-docker
    channel: msys2-ci
    server:
      host: irc.oftc.net
      port: 6667

publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: teaci/msys32
    tag:
      - "latest"
      - "w1.9.5-m2.5.0-6"
    when:
      repo: fracting/msys32-docker
      branch: master
