#!/bin/bash

set -e

. /etc/msys32-env

# hack - wineboot without display, create wineprefix in a quick way, workaround wineboot event timeout waiting for gecko and mono
WINEDEBUG=-all DISPLAY=:55.0 wineboot; wineserver -w
WINEDEBUG=-all DISPLAY=:55.0 winetricks nocrashdialog; wineserver -w
WINEDEBUG=-all DISPLAY=:55.0 winetricks shcore=disabled; wineserver -w # workaround https://bugs.wine-staging.com/show_bug.cgi?id=642

if test -d ${MSYS_ROOT}
then
    echo Already Initialized. 
else
    pushd ~/.wine/drive_c
    wget http://54.201.206.112/msys2/distrib/i686/msys2-base-i686-20150916.tar.xz
    tar xf msys2-base-i686-20150916.tar.xz
    msys32 -c echo Init MSYS2 done.
    echo "Server = http://54.201.206.112/msys2/mingw/i686" > ${MSYS_ROOT}/etc/pacman.d/mirrorlist.mingw32
    echo "Server = http://54.201.206.112/msys2/msys/\$arch" > ${MSYS_ROOT}/etc/pacman.d/mirrorlist.msys
    msys32 -c update-core || true
    msys32 -c update-core || true
    msys32 -c update-core || true
    msys32 -c update-core
    echo "Server = http://54.201.206.112/msys2/mingw/i686" > ${MSYS_ROOT}/etc/pacman.d/mirrorlist.mingw32
    echo "Server = http://54.201.206.112/msys2/msys/\$arch" > ${MSYS_ROOT}/etc/pacman.d/mirrorlist.msys
    msys32 -c pacman -Su --needed --noconfirm || true
    msys32 -c pacman -Su --needed --noconfirm || true
    msys32 -c pacman -Su --needed --noconfirm || true
    msys32 -c pacman -Su --needed --noconfirm
    echo "Server = http://54.201.206.112/msys2/mingw/i686" > ${MSYS_ROOT}/etc/pacman.d/mirrorlist.mingw32
    echo "Server = http://54.201.206.112/msys2/msys/\$arch" > ${MSYS_ROOT}/etc/pacman.d/mirrorlist.msys
    msys32 -c pacman -S --needed --noconfirm base-devel msys2-devel mingw-w64-i686-toolchain git subversion || true
    msys32 -c pacman -S --needed --noconfirm base-devel msys2-devel mingw-w64-i686-toolchain git subversion || true
    msys32 -c pacman -S --needed --noconfirm base-devel msys2-devel mingw-w64-i686-toolchain git subversion || true
    msys32 -c pacman -S --needed --noconfirm base-devel msys2-devel mingw-w64-i686-toolchain git subversion
    popd
fi
